[SERVICE]
    flush        2
    daemon       off
    http_server  on
    log_level    info
    parsers_file parsers.conf

    Storage.type filesystem
    Storage.path /var/log/fluent-bit/
    Storage.sync normal
    Storage.backlog.mem_limit 150M
    Storage.Max_Chunks_up 128
    Mem_Buf_Limit 200MB

# 接收 Docker 容器日志（可选）
[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

# -----------------------
# 采集业务日志（文本/混合日志）
# -----------------------
# dicegame logs
[INPUT]
    Name              tail
    Path              /opt/dicegame_trial_server/logs/*.log
    Path_Key          filename
    Tag               dicegame_trial_server
    Ignore_Older      172800
    Refresh_Interval  10
    Mem_Buf_Limit     100MB
    Skip_Long_Lines   On
    Parser            plain_text
    DB                /var/log/fluent-bit/dicegame_trial_server.db
    DB.Sync           Full

# -----------------------
# 输出到 Elasticsearch
# -----------------------
[OUTPUT]
    Name            es
    Match           *
    Host            ${FLB_ES_HOST}
    Port            ${FLB_ES_PORT}
    Index           diceashui-logs
    tls             On
    Logstash_Format Off
    Retry_Limit     False
    Suppress_Type_Name On       
    Include_Tag_Key    On
    Tag_Key            tag
    Http_User elastic
    Http_Passwd ${ELASTIC_PASSWORD}
    Buffer_Size       11MB          # 减小单次 flush 大小
    compress gzip
